version: "2"
services:
  overworld:
    image: dstacademy/dontstarvetogether:0.8
    container_name: overworld
    hostname: overworld
    tty: true
    stdin_open: true
    command: dst-server start --update=all
    env_file: overworld.env
    environment:
      # Defined in YAML because multi-line support, but this can also be injected other ways
      # From a vanilla survival leveldataoverride.lua
      LEVELDATA_OVERRIDES: |
        return {
          desc="The standard Don't Starve experience.",
          hideminimap=false,
          id="SURVIVAL_TOGETHER",
          location="forest",
          max_playlist_position=999,
          min_playlist_position=0,
          name="Default",
          numrandom_set_pieces=4,
          ordered_story_setpieces={ "Sculptures_1", "Maxwell5" },
          override_level_string=false,
          overrides={
            alternatehunt="default",
            angrybees="default",
            antliontribute="default",
            autumn="default",
            bearger="default",
            beefalo="default",
            beefaloheat="default",
            bees="default",
            berrybush="default",
            birds="default",
            boons="default",
            branching="default",
            butterfly="default",
            buzzard="default",
            cactus="default",
            carrot="default",
            catcoon="default",
            chess="default",
            day="default",
            deciduousmonster="default",
            deerclops="default",
            disease_delay="default",
            dragonfly="default",
            flint="default",
            flowers="default",
            frograin="default",
            goosemoose="default",
            grass="default",
            houndmound="default",
            hounds="default",
            hunt="default",
            krampus="default",
            layout_mode="LinkNodesByKeys",
            liefs="default",
            lightning="default",
            lightninggoat="default",
            loop="default",
            lureplants="default",
            marshbush="default",
            merm="default",
            meteorshowers="default",
            meteorspawner="default",
            moles="default",
            mushroom="default",
            penguins="default",
            perd="default",
            petrification="default",
            pigs="default",
            ponds="default",
            prefabswaps_start="default",
            rabbits="default",
            reeds="default",
            regrowth="default",
            roads="default",
            rock="default",
            rock_ice="default",
            sapling="default",
            season_start="default",
            specialevent="default",
            spiders="default",
            spring="default",
            start_location="default",
            summer="default",
            tallbirds="default",
            task_set="default",
            tentacles="default",
            touchstone="default",
            trees="default",
            tumbleweed="default",
            walrus="default",
            weather="default",
            wildfires="default",
            winter="default",
            world_size="default",
            wormhole_prefab="wormhole"
          },
          random_set_pieces={
            "Sculptures_2",
            "Sculptures_3",
            "Sculptures_4",
            "Sculptures_5",
            "Chessy_1",
            "Chessy_2",
            "Chessy_3",
            "Chessy_4",
            "Chessy_5",
            "Chessy_6",
            "Maxwell1",
            "Maxwell2",
            "Maxwell3",
            "Maxwell4",
            "Maxwell6",
            "Maxwell7",
            "Warzone_1",
            "Warzone_2",
            "Warzone_3"
          },
          required_prefabs={ "multiplayer_portal" },
          substitutes={  },
          version=3
        }
    ports:
      - "10999:10999/udp"
    volumes:
      - ./overworld:/var/lib/dsta/cluster
  underworld:
    image: dstacademy/dontstarvetogether:0.8
    container_name: underworld
    hostname: underworld
    tty: true
    stdin_open: true
    command: dst-server start --update=all
    env_file: underworld.env
    environment:
      # Defined in YAML because multi-line support, but this can also be injected other ways
      # From a vanilla caves leveldataoverride.lua
      LEVELDATA_OVERRIDES: |
        return {
          background_node_range={ 0, 1 },
          desc="Delve into the caves... together!",
          hideminimap=false,
          id="DST_CAVE",
          location="cave",
          max_playlist_position=999,
          min_playlist_position=0,
          name="The Caves",
          numrandom_set_pieces=0,
          override_level_string=false,
          overrides={
            banana="default",
            bats="default",
            berrybush="default",
            boons="default",
            branching="default",
            bunnymen="default",
            cave_ponds="default",
            cave_spiders="default",
            cavelight="default",
            chess="default",
            disease_delay="default",
            earthquakes="default",
            fern="default",
            fissure="default",
            flint="default",
            flower_cave="default",
            grass="default",
            layout_mode="RestrictNodesByKey",
            lichen="default",
            liefs="default",
            loop="default",
            marshbush="default",
            monkey="default",
            mushroom="default",
            mushtree="default",
            petrification="default",
            prefabswaps_start="default",
            reeds="default",
            regrowth="default",
            roads="never",
            rock="default",
            rocky="default",
            sapling="default",
            season_start="default",
            slurper="default",
            slurtles="default",
            start_location="caves",
            task_set="cave_default",
            tentacles="default",
            touchstone="default",
            trees="default",
            weather="default",
            world_size="default",
            wormattacks="default",
            wormhole_prefab="tentacle_pillar",
            wormlights="default",
            worms="default"
          },
          required_prefabs={ "multiplayer_portal" },
          substitutes={  },
          version=3
        }
    ports:
      - "11000:11000/udp"
    links:
      - overworld
    volumes:
      - ./underworld:/var/lib/dsta/cluster
